### ISSUE TITLE
BUG: OpenVV() relies on global 'element' variable

### ISSUE THREAD

**Issue by vladgurgov** [InteractiveAdvertisingBureau/openvv-html#10]
if you rename 'element' to 'el' in demo.js 
`var openvv = new OpenVV(), el = document.getElementById('elementToMeasure');

var executor = openvv
  .measureElement(el) ...`

you will get exception:
`MeasurementExecutor.js:164 Uncaught ReferenceError: element is not defined
    at MeasurementExecutor._instantiateTechnique (MeasurementExecutor.js:164)
    at Array.map (<anonymous>)
    at MeasurementExecutor._selectTechnique (MeasurementExecutor.js:153)
    at new MeasurementExecutor (MeasurementExecutor.js:34)
    at OpenVV.measureElement (OpenVV.js:28)
    at demo.js:22`

I have a patch PR for it, will add it a bit later...

**Comment by jdreetz** [comment]
We could wrap the demo code in an IIFE, but it's really just meant to be a simple example of how to use library. This isn't source code for the library itself.

**Comment by vladgurgov** [comment]
fix PR https://github.com/InteractiveAdvertisingBureau/openvv-html/pull/11

**Comment by vladgurgov** [comment]
@jdreetz there is a bug (typo) in MeasurementExecutor - using global var element instead of this._element 

see PR for a fix.

**Comment by jdreetz** [comment]
Good catch! I misunderstood your original comment.
